apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dapr-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://dapr.github.io/helm-charts/'
    targetRevision: 1.13.5
    helm:
      releaseName: dapr
    chart: dapr
  destination:
    name: 'dev-cluster'
    namespace: dapr-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true